networks:
  default:
    name: mosaic-tier
    external: true

services:
  api:
    container_name: backend-app
    restart: always
    env_file:
      - ./prod.env
    ports:
      - '8080:3000'
    build:
      dockerfile: ./apps/api/Dockerfile
