networks:
  default:
    name: mosaic-tier
    external: true

services:
  api:
    container_name: mosaic-app
    restart: always
    ports:
      - '8080:3000'
    build:
      dockerfile: ./apps/api/Dockerfile
