name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Decode and create .config file from secret
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: '.config.ts'
          fileDir: './apps/api/src/'
          encodedString: ${{ secrets.CONFIG_FILE_BASE64 }}

      - name: List specific directory
        run: ls ./apps/api/src/    

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mosaic-api:${{ github.sha }}

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop mosaic-api || true
            docker rm mosaic-api || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/mosaic-api:${{ github.sha }}
            docker run -d --name mosaic-api --network=db-network \
              -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/mosaic-api:${{ github.sha }}
